/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.movie;

import controller.MovieController;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import view.actor.ActorQueryScreen;
import view.actor.ActorRegistrationScreen;
import view.actorFilm.ActorMovieAssociation;

public class MovieRegistrationScreen extends javax.swing.JFrame {

    private JFrame previousScreen;
    
    /**
     * Creates new form MainScreen
     */
    public MovieRegistrationScreen() {
        initComponents();
    }
    
    public MovieRegistrationScreen(JFrame previousScreen) {
        initComponents();
        this.previousScreen = previousScreen;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jComboBoxGenre = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextFieldReleaseDate = new javax.swing.JFormattedTextField();
        jButtonSave = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldMovieName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaSynopsis = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuRegister = new javax.swing.JMenu();
        jMenuActorRegister = new javax.swing.JMenuItem();
        jMenuQuery = new javax.swing.JMenu();
        jMenuActorQuery = new javax.swing.JMenuItem();
        jMenuMovieQuery = new javax.swing.JMenuItem();
        jMenuAssociation = new javax.swing.JMenu();
        jMenuExit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Movie Register");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                closeWindow(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel2.setText("Genre: ");

        jComboBoxGenre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Action", "Animation", "Adventure", "Art cinema", "Comedy", "Romantic comedy", "Dramatic comedy", "Action comedy", "Dance", "Documentary", "Drama", "Espionage", "Western", "Scientific fantasy", "Science fiction", "War films", "Musical", "Crime film", "Romance", "Sitcom", "Thriller", "Horror" }));

        jLabel3.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel3.setText("Synopsis");

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel4.setText("releaseDate");

        try {
            jFormattedTextFieldReleaseDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMovie(evt);
            }
        });

        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearFields(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelRegistration(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel1.setText("Movie name:");

        jLabel5.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        jLabel5.setText("Movie Registration");

        jTextAreaSynopsis.setColumns(20);
        jTextAreaSynopsis.setRows(5);
        jScrollPane1.setViewportView(jTextAreaSynopsis);

        jMenuRegister.setText("Register");

        jMenuActorRegister.setText("Actor");
        jMenuActorRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openActorRegistration(evt);
            }
        });
        jMenuRegister.add(jMenuActorRegister);

        jMenuBar1.add(jMenuRegister);

        jMenuQuery.setText("Query");

        jMenuActorQuery.setText("Actor");
        jMenuActorQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openActorQuery(evt);
            }
        });
        jMenuQuery.add(jMenuActorQuery);

        jMenuMovieQuery.setText("Movie");
        jMenuMovieQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMovieQuery(evt);
            }
        });
        jMenuQuery.add(jMenuMovieQuery);

        jMenuBar1.add(jMenuQuery);

        jMenuAssociation.setText("Association");
        jMenuAssociation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuAssociationopenActorMovieAssociation(evt);
            }
        });
        jMenuBar1.add(jMenuAssociation);

        jMenuExit.setText("Exit");
        jMenuExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit(evt);
            }
        });
        jMenuBar1.add(jMenuExit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonSave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonClear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonCancel))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFormattedTextFieldReleaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldMovieName, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(252, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldMovieName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jFormattedTextFieldReleaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSave)
                    .addComponent(jButtonClear)
                    .addComponent(jButtonCancel))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveMovie(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMovie
        // TODO add your handling code here:

        boolean success;

        String name = jTextFieldMovieName.getText();
        String genre = jComboBoxGenre.getSelectedItem().toString();
        String synopsis = jTextAreaSynopsis.getText();
        String releaseDate = jFormattedTextFieldReleaseDate.getText();

        try {
            MovieController movieController = new MovieController();

            success = movieController.registerMovie(name, genre, synopsis, releaseDate);

            if (success) {
                JOptionPane.showMessageDialog(null, "Successfully registered movie!");
                this.clearFields(evt);
            } else {
                JOptionPane.showMessageDialog(null, "Error registering movie");

            }

        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_saveMovie

    private void openMovieQuery(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMovieQuery
        this.setVisible(false);
        MovieQueryScreen movieQueryScreen = new MovieQueryScreen(this);
        movieQueryScreen.setVisible(true);
    }//GEN-LAST:event_openMovieQuery

    
    private void clearFields(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearFields
        jTextFieldMovieName.setText("");
        jComboBoxGenre.setSelectedIndex(0);
        jTextAreaSynopsis.setText("");
        jFormattedTextFieldReleaseDate.setText("");
    }//GEN-LAST:event_clearFields

    private void closeWindow(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeWindow
        this.dispose();
        previousScreen.setVisible(true);
    }//GEN-LAST:event_closeWindow

    private void cancelRegistration(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelRegistration
        this.dispose();
        previousScreen.setVisible(true);
    }//GEN-LAST:event_cancelRegistration

    private void exit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit
        System.exit(0);
    }//GEN-LAST:event_exit

    private void jMenuAssociationopenActorMovieAssociation(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuAssociationopenActorMovieAssociation
        this.setVisible(false);
        ActorMovieAssociation actorMovieAssociation = new ActorMovieAssociation(this);
        actorMovieAssociation.setVisible(true);
    }//GEN-LAST:event_jMenuAssociationopenActorMovieAssociation

    private void openActorRegistration(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openActorRegistration
        this.setVisible(false);
        ActorRegistrationScreen actorRegistrationScreen = new ActorRegistrationScreen(this);
        actorRegistrationScreen.setVisible(true);
    }//GEN-LAST:event_openActorRegistration

    private void openActorQuery(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openActorQuery
        this.setVisible(false);
        ActorQueryScreen actorQueryScreen = new ActorQueryScreen(this);
        actorQueryScreen.setVisible(true);
    }//GEN-LAST:event_openActorQuery

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieRegistrationScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieRegistrationScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieRegistrationScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieRegistrationScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieRegistrationScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox<String> jComboBoxGenre;
    private javax.swing.JFormattedTextField jFormattedTextFieldReleaseDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuItem jMenuActorQuery;
    private javax.swing.JMenuItem jMenuActorRegister;
    private javax.swing.JMenu jMenuAssociation;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuExit;
    private javax.swing.JMenuItem jMenuMovieQuery;
    private javax.swing.JMenu jMenuQuery;
    private javax.swing.JMenu jMenuRegister;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaSynopsis;
    private javax.swing.JTextField jTextFieldMovieName;
    // End of variables declaration//GEN-END:variables
}
