/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.actor;

import java.sql.SQLIntegrityConstraintViolationException;
import controller.ActorController;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import model.Actor;
import view.actorFilm.ActorMovieAssociation;
import view.movie.MovieQueryScreen;
import view.movie.MovieRegistrationScreen;

public class ActorQueryScreen extends javax.swing.JFrame {

    private JFrame previousScreen;
    ActorEditScreen actorEditScreen = new ActorEditScreen(this);

    /**
     * Creates new form MainScreen
     */
    public ActorQueryScreen() {
        initComponents();
        initSearch();
    }

    public ActorQueryScreen(JFrame previousScreen) {
        initComponents();
        this.previousScreen = previousScreen;
        initSearch();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableActorQuery = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldActorName = new javax.swing.JTextField();
        jButtonQuery = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonDelete = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuRegister = new javax.swing.JMenu();
        jMenuActorRegister = new javax.swing.JMenuItem();
        jMenuMovieRegister = new javax.swing.JMenuItem();
        jMenuQuery = new javax.swing.JMenu();
        jMenuMovieQuery = new javax.swing.JMenuItem();
        jMenuAssociation = new javax.swing.JMenu();
        jMenuExit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Actor Query");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                closeWindow(evt);
            }
        });

        jTableActorQuery.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Name", "Gender", "Nationality", "Birth Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableActorQuery);

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel1.setText("Actor name:");

        jButtonQuery.setText("Query");
        jButtonQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                queryActor(evt);
            }
        });

        jButtonEdit.setText("Edit");
        jButtonEdit.setEnabled(false);
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEdit(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        jLabel2.setText("Actor Query");

        jButtonDelete.setText("Delete");
        jButtonDelete.setEnabled(false);
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelete(evt);
            }
        });

        jMenuRegister.setText("Register");

        jMenuActorRegister.setText("Actor");
        jMenuActorRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openActorRegister(evt);
            }
        });
        jMenuRegister.add(jMenuActorRegister);

        jMenuMovieRegister.setText("Movie");
        jMenuMovieRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMovieRegistration(evt);
            }
        });
        jMenuRegister.add(jMenuMovieRegister);

        jMenuBar1.add(jMenuRegister);

        jMenuQuery.setText("Query");

        jMenuMovieQuery.setText("Movie");
        jMenuMovieQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMovieQuery(evt);
            }
        });
        jMenuQuery.add(jMenuMovieQuery);

        jMenuBar1.add(jMenuQuery);

        jMenuAssociation.setText("Association");
        jMenuAssociation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuAssociationopenActorMovieAssociation(evt);
            }
        });
        jMenuBar1.add(jMenuAssociation);

        jMenuExit.setText("Exit");
        jMenuExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit(evt);
            }
        });
        jMenuBar1.add(jMenuExit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jTextFieldActorName, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonQuery)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDelete)
                .addGap(178, 178, 178))
            .addGroup(layout.createSequentialGroup()
                .addGap(343, 343, 343)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEdit)
                    .addComponent(jButtonQuery)
                    .addComponent(jTextFieldActorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeWindow(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeWindow
        this.dispose();
        previousScreen.setVisible(true);
    }//GEN-LAST:event_closeWindow

    private void initSearch() {
        jTextFieldActorName.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                updateTable();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateTable();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                updateTable();
            }

            private void updateTable() {
                String name = jTextFieldActorName.getText();
                searchActor(name);
            }
        });
    }

    private void searchActor(String name) {
        DefaultTableModel tableModel = (DefaultTableModel) jTableActorQuery.getModel();
        tableModel.setNumRows(0);

        jTableActorQuery.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 1) {
                    jButtonEdit.setEnabled(true);
                    jButtonDelete.setEnabled(true);
                } else {
                    jButtonEdit.setEnabled(false);
                    jButtonDelete.setEnabled(false);
                }
            }
        });

        try {
            ActorController actorController = new ActorController();
            ArrayList<Actor> actors = actorController.listActors(name);

            for (Actor actor : actors) {
                tableModel.addRow(new Object[]{
                    actor.getId(),
                    actor.getName(),
                    actor.getGender(),
                    actor.getNationality(),
                    actor.getBirthDate()});
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    private void queryActor(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queryActor
        String name = jTextFieldActorName.getText();
        searchActor(name);
    }//GEN-LAST:event_queryActor

    private void openActorRegister(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openActorRegister
        this.setVisible(false);
        ActorRegistrationScreen actorRegistrationScreen = new ActorRegistrationScreen(this);
        actorRegistrationScreen.setVisible(true);
    }//GEN-LAST:event_openActorRegister

    private void jButtonEdit(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEdit

        int id = (Integer) jTableActorQuery.getModel().getValueAt(jTableActorQuery.getSelectedRow(), 0);
        String name = (String) jTableActorQuery.getModel().getValueAt(jTableActorQuery.getSelectedRow(), 1);
        String gender = (String) jTableActorQuery.getModel().getValueAt(jTableActorQuery.getSelectedRow(), 2);
        String nationality = (String) jTableActorQuery.getModel().getValueAt(jTableActorQuery.getSelectedRow(), 3);
        Date birthDate = (Date) jTableActorQuery.getModel().getValueAt(jTableActorQuery.getSelectedRow(), 4);

        actorEditScreen.getData(id, name, gender, nationality, birthDate);

        this.setVisible(false);
        actorEditScreen.setVisible(true);
    }//GEN-LAST:event_jButtonEdit

    private void jButtonDelete(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelete

        boolean success;

        int id = (Integer) jTableActorQuery.getModel().getValueAt(jTableActorQuery.getSelectedRow(), 0);
        String ActorNameTable = (String) jTableActorQuery.getModel().getValueAt(jTableActorQuery.getSelectedRow(), 1);

        try {
            ActorController actorController = new ActorController();

            int response = JOptionPane.showConfirmDialog(null, String.format("Do you want to delete the actor %s?", ActorNameTable), "Confirm", JOptionPane.YES_NO_OPTION);

            if (response == JOptionPane.YES_OPTION) {
                success = actorController.deleteActor(id);
                if (success) {
                    JOptionPane.showMessageDialog(null, "Successfully deleted actor!");
                    String name = jTextFieldActorName.getText();
                    searchActor(name);
                } else {
                    JOptionPane.showMessageDialog(null, "Error deleting actor");
                }
            }

        } catch (SQLIntegrityConstraintViolationException e) {
            JOptionPane.showMessageDialog(null, String.format("Error deleting the actor '%s'. This actor is associated with a movie.", ActorNameTable));

        }
    }//GEN-LAST:event_jButtonDelete

    private void exit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit
        System.exit(0);
    }//GEN-LAST:event_exit

    private void jMenuAssociationopenActorMovieAssociation(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuAssociationopenActorMovieAssociation
        this.setVisible(false);
        ActorMovieAssociation actorMovieAssociation = new ActorMovieAssociation(this);
        actorMovieAssociation.setVisible(true);
    }//GEN-LAST:event_jMenuAssociationopenActorMovieAssociation

    private void openMovieRegistration(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMovieRegistration
        this.setVisible(false);
        MovieRegistrationScreen movieRegistrationScreen = new MovieRegistrationScreen(this);
        movieRegistrationScreen.setVisible(true);
    }//GEN-LAST:event_openMovieRegistration

    private void openMovieQuery(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMovieQuery
        this.setVisible(false);
        MovieQueryScreen movieQueryScreen = new MovieQueryScreen(this);
        movieQueryScreen.setVisible(true);
    }//GEN-LAST:event_openMovieQuery

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActorQueryScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActorQueryScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActorQueryScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActorQueryScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActorQueryScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonQuery;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMenuActorRegister;
    private javax.swing.JMenu jMenuAssociation;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuExit;
    private javax.swing.JMenuItem jMenuMovieQuery;
    private javax.swing.JMenuItem jMenuMovieRegister;
    private javax.swing.JMenu jMenuQuery;
    private javax.swing.JMenu jMenuRegister;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableActorQuery;
    private javax.swing.JTextField jTextFieldActorName;
    // End of variables declaration//GEN-END:variables

}
